-- TODO: MAKE THIS A STORED PROCEDURE
-- TODO: THIS SHOULD NOTIFY NEW USER SUBMISSION
CREATE OR REPLACE FUNCTION facial_recognition_retrieve(
	
) RETURNS INTEGER AS $$
BEGIN

	RETURN 1;

END;
$$
LANGUAGE plpgsql;